/*
 * API whatsgate.ru
 *
 * Интерфейс для взаимодействия с клиентом Whatsapp
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SendBody struct {
	// Service Whatsapp ID
	WhatsappID string `json:"WhatsappID"`
	// Async query returns Message Object
	Async bool `json:"async,omitempty"`
	Recipient *AnyOfsendBodyRecipient `json:"recipient,omitempty"`
	Message *AnyOfsendBodyMessage `json:"message,omitempty"`
}
