/*
 * API whatsgate.ru
 *
 * Интерфейс для взаимодействия с клиентом Whatsapp
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type RecipientNum struct {
	// Recipient number
	Number string `json:"number"`
	// Recipient type, group or contact
	Type_ string `json:"type,omitempty"`
}
