/*
 * API whatsgate.ru
 *
 * Интерфейс для взаимодействия с клиентом Whatsapp
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CheckBody struct {
	// Идентификатор Whatsapp ID
	WhatsappID string `json:"WhatsappID,omitempty"`
	// Номер в формате 79999999999
	Number string `json:"number,omitempty"`
}
