/*
 * API whatsgate.ru
 *
 * Интерфейс для взаимодействия с клиентом Whatsapp
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse2002 struct {
	// при удачном исполнении запроса содержит OK
	Result string `json:"result,omitempty"`
	// массив объектов ResponseChat
	Data []ResponseChat `json:"data,omitempty"`
}
