/*
 * API whatsgate.ru
 *
 * Интерфейс для взаимодействия с клиентом Whatsapp
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ResponseChat struct {
	// Идентификатор контакта или группы в формате WhatsApp
	Id string `json:"id,omitempty"`
	// Имя контакта или группы
	Name string `json:"name,omitempty"`
	// Является ли чат контактом или группой
	IsGroup bool `json:"isGroup,omitempty"`
	// Является ли чат ReadOnly
	IsReadOnly bool `json:"isReadOnly,omitempty"`
	// Количество непрочитанных сообщений в чате
	UnreadCount int32 `json:"unreadCount,omitempty"`
	// Время последней активночти в чате
	Timestamp int32 `json:"timestamp,omitempty"`
	// Является ли чат закрепленным
	Pinned bool `json:"pinned,omitempty"`
	// Выключен ли у чата звук
	IsMuted bool `json:"isMuted,omitempty"`
	// Время, оставшееся до включения звука
	MuteExpiration bool `json:"muteExpiration,omitempty"`
	GroupMetadata *ResponseChatGroupMetadata `json:"groupMetadata,omitempty"`
}
