/*
 * API whatsgate.ru
 *
 * Интерфейс для взаимодействия с клиентом Whatsapp
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MessageMedia struct {
	Body string `json:"body,omitempty"`
	Quote string `json:"quote,omitempty"`
	Type_ string `json:"type,omitempty"`
	Media *Media `json:"media,omitempty"`
}
