/*
 * API whatsgate.ru
 *
 * Интерфейс для взаимодействия с клиентом Whatsapp
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ModelError struct {
	// Наименование ошибки
	Name string `json:"name,omitempty"`
	// Текст ошибки
	Message string `json:"message,omitempty"`
	Code int32 `json:"code,omitempty"`
	Status int32 `json:"status,omitempty"`
}
