/*
 * API whatsgate.ru
 *
 * Интерфейс для взаимодействия с клиентом Whatsapp
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Media struct {
	// Mime type of file
	Mimetype string `json:"mimetype"`
	// Base64 encoded data file body
	Data string `json:"data"`
	// Name of the file
	Filename string `json:"filename"`
}
